using System.IO;
using System.Windows;
using System.Windows.Controls;
namespace Papergraph;

public static class SelectionTests
{
    public static void Run()
    {
        void Check(bool pass,string reason){if(!pass)throw new Exception(reason);}
        var doc=new GraphDocument{Nodes=[new(){Id="a",X=-25,Y=40,Title="甲"},new(){Id="b",X=75,Y=40,Title="乙"},new(){Id="c",X=375,Y=40,Title="丙"}],Edges=[new(){From="a",To="b"},new(){From="b",To="c"}]};
        var data=Path.Combine(Path.GetTempPath(),"yujian-selection-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(data);Storage.Save(Path.Combine(data,"Example.papergraph"),doc);var window=new MainWindow(data);var graph=window.Graph;graph.SetView(1,new Point());
        void Box(Point a,Point b,bool additive=false){graph.BeginBoxSelection(a,additive);graph.UpdateBoxSelection(b);graph.FinishBoxSelection();}
        void Select()=>Box(new Point(60,50),new Point(250,150));
        void Click(Button button)=>button.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));
        void Undo()=>window.EditMenu.Items.OfType<MenuItem>().Single(m=>(string)m.Header=="Undo").RaiseEvent(new RoutedEventArgs(MenuItem.ClickEvent));
        var original=graph.Document.Serialize();Select();Check(graph.Selected.SetEquals(["a","b"]),"Rectangle selects multiple points");Check(graph.Document.Serialize()==original,"Selection never creates a threshold or changes data");
        Check(graph.GroupSelection&&window.MultiBar.Visibility==Visibility.Visible,"Rectangle immediately enables group movement and bottom actions");Check(window.RegionButton.IsEnabled&&window.CircleButton.IsEnabled&&window.DeleteButton.IsEnabled,"Three footer actions available for connected selection");
        Check(((StackPanel)window.MultiBar.Child).Children.OfType<Button>().Count()==3&&window.RegionButton.Content is ObjectGlyph{Kind:"frame"}&&window.CircleButton.Content is ObjectGlyph{Kind:"circle"}&&(string)window.DeleteButton.Content=="Delete","Footer retains exactly three actions with symbols for graph groups");
        Box(new Point(460,50),new Point(550,150),true);Check(graph.Selected.SetEquals(["a","b","c"]),"Additive rectangle retains previous selection");Check(graph.SelectionBox!.Value.Contains(GraphStyle.Center(graph.Document.Node("a")!)),"Additive frame creation range includes prior selection");
        graph.BeginBoxSelection(new Point(900,900),false);graph.UpdateBoxSelection(new Point(950,950));Check(graph.SelectionCount==0,"Empty rectangle clears selection only");graph.CancelBoxSelection();Check(graph.Selected.SetEquals(["a","b","c"]),"Cancel restores previous multi-selection");
        Select();Click(window.RegionButton);Check(graph.Document.Regions.Count==1&&GraphBoard.Bounds(graph.Document.Regions.Single())==new Rect(60,50,190,100)&&graph.Document.Nodes.Count==3,"Footer creates exact drawn threshold without changing points");Undo();Check(graph.Document.Serialize()==original,"Threshold undo is lossless");
        Select();Click(window.CircleButton);var circle=graph.Document.Nodes.Single(n=>n.Kind=="circle");Check(graph.Document.Visible(circle.Id).Select(n=>n.Id).ToHashSet().SetEquals(["a","b"])&&graph.Document.Regions.Count==0,"Footer creates double ring without implicit threshold");Undo();Check(graph.Document.Serialize()==original,"Merge undo is lossless");
        Select();Click(window.DeleteButton);Check(graph.Document.Nodes.Count==1&&graph.Document.Node("c")!=null&&graph.Document.Edges.Count==0,"Bulk delete removes selected points and their incident edges only");Undo();Check(graph.Document.Serialize()==original,"Bulk delete undo restores exact graph");
        graph.Selected=["a","c"];Box(new Point(800,800),new Point(820,820),true);Check(!window.CircleButton.IsEnabled&&window.DeleteButton.IsEnabled,"Disconnected selection retains bulk actions while merge is disabled");
        graph.Document.Regions.AddRange([new(){Id="frame-a",Title="甲框内容",IsAbsolute=true,X=0,Y=0,Width=300,Height=200},new(){Id="frame-b",Title="乙框内容",IsAbsolute=true,X=150,Y=20,Width=200,Height=200},new(){Id="nested",Title="小框",IsAbsolute=true,X=20,Y=20,Width=50,Height=50},new(){Id="outside",IsAbsolute=true,X=900,Y=0,Width=120,Height=100}]);graph.RefreshData();Select();Check(graph.SelectedRegions.Count==0,"Selecting points inside a larger frame does not accidentally select that frame");
        void Mixed()=>Box(new Point(-30,-30),new Point(380,250));Mixed();Check(graph.Selected.SetEquals(["a","b"])&&graph.SelectedRegions.SetEquals(["frame-a","frame-b","nested"]),"Mixed marquee selects contained overlapping and nested frames with points");
        var before=graph.Document.Serialize();var boxBefore=graph.SelectionBox!.Value;graph.BeginSelectionMove();graph.MoveSelection(new Vector(20,15));graph.MoveSelection(new Vector(30,25));graph.EndSelectionMove();
        Check(GraphStyle.Center(graph.Document.Node("b")!)==new Point(230,125),"Shared point moves once, not once per selected frame");Check(graph.Document.Regions.Single(r=>r.Id=="frame-a").X==30&&graph.Document.Regions.Single(r=>r.Id=="frame-b").X==180&&graph.Document.Regions.Single(r=>r.Id=="nested").X==50,"Selected frames move together from original positions");Check(graph.Document.Node("c")!.X==375&&graph.Document.Regions.Single(r=>r.Id=="outside").X==900,"Unselected objects stay fixed");var movedBox=boxBefore;movedBox.Offset(30,25);Check(graph.SelectionBox==movedBox,"Marquee follows moved objects");
        var movedDocument=graph.Document.Serialize();Click(window.DeleteButton);Check(graph.Document.Nodes.Count==1&&graph.Document.Regions.Single().Id=="outside","Mixed delete handles all selected frames and nodes in one action");Undo();Check(graph.Document.Serialize()==movedDocument,"Mixed delete undo restores coordinates and frame content exactly");
        graph.Selected=[];graph.SelectedRegions=["frame-a","frame-b"];Box(new Point(800,800),new Point(820,820),true);Check(!window.CircleButton.IsEnabled&&window.DeleteButton.IsEnabled,"Frame-only multiselect supports deletion");Click(window.DeleteButton);Check(graph.Document.Nodes.Count==3&&graph.Document.Edges.Count==2&&graph.Document.Regions.Count==2,"Deleting only frames leaves their unselected points and links intact");Undo();Check(graph.Document.Serialize()==movedDocument,"Frame-only delete undo is lossless");
        Mixed();var frameIds=graph.SelectedRegions.ToHashSet();Click(window.CircleButton);circle=graph.Document.Nodes.Single(n=>n.Kind=="circle");Check(graph.Document.Regions.Where(r=>frameIds.Contains(r.Id)).All(r=>r.Parent==circle.Id),"Selected frames accompany connected nodes into the double ring");window.Enter(circle.Id);Check(graph.VisibleRegions.Select(r=>r.Id).ToHashSet().SetEquals(frameIds),"Entering merged graph reveals selected frames and their notes");window.Leave();Undo();Check(graph.Document.Serialize()==movedDocument,"Mixed merge undo restores the entire graph");
        Mixed();var savedRegions=graph.SelectedRegions.ToHashSet();var savedBox=graph.SelectionBox;graph.BeginBoxSelection(new Point(1000,1000),false);graph.UpdateBoxSelection(new Point(1010,1010));graph.CancelBoxSelection();Check(graph.SelectedRegions.SetEquals(savedRegions)&&graph.SelectionBox==savedBox,"Cancel preserves mixed selection and its movement area");
        window.Close();File.AppendAllText(Path.Combine(AppContext.BaseDirectory,"test-results.txt"),"PASS: immediate mixed selection with exactly three footer actions, no implicit frame, additive range, cancellation, selected-frame containment, rigid movement of overlapping/nested frames and shared points, moving marquee, mixed/frame-only delete, merge with frame notes, and lossless undo.\n");
    }
}
